[theme]
base = "light"
primaryColor = "#2453D6"
backgroundColor = "#EEF1F6"
secondaryBackgroundColor = "#E4E9F1"
textColor = "#0B1B33"
borderColor = "#D8DFEA"
baseRadius = "10px"
font = "Poppins:https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap, sans-serif"
headingFont = "Unbounded:https://fonts.googleapis.com/css2?family=Unbounded:wght@500;600;700&display=swap, sans-serif"

[server]
headless = true
